{
  "$schema": "https://json.schemastore.org/railway.json",
  "build": {
    "builder": "NIXPACKS_BUILDER",
    "buildCommand": "npm run build",
    "startCommand": "npm run start",
    "cache": {
      "node": "yes"
    }
  },
  "deploy": {
    "numReplicas": 1
  }
}